name: Container-Deploy

on:
  push:
    branches: [main]
    paths:
      - "packages/container/**"

defaults:
  run:
    working-directory: packages/container

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install App dependencies
        run: npm install
        
      - name: Build dependencies
        run: npm run build

      - name: Deploying application to Amazon S3
        uses: dvelasquez/deploy-s3-action@main
      - run: aws s3 sync dist s3://micro-frontend-apps/container/latest
        env:
          AWS_ACCESS_KEY_ID: AKIAUANFRSDIWHTIAYZR
          AWS_SECRET_ACCESS_KEY: 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
